In [10]:
import numpy as np
import random
import matplotlib.pyplot as plt
from matplotlib import cm
from IPython import display
import itertools
from time import sleep

In [95]:
c = ([tuple(x) for x in itertools.combinations_with_replacement(np.arange(10), 2)])
d = random.sample(range(len(c)),len(c))
print(d)

[50, 33, 4, 47, 16, 43, 48, 27, 5, 54, 35, 18, 42, 20, 34, 30, 8, 38, 11, 9, 14, 45, 22, 29, 46, 7, 0, 1, 51, 21, 28, 17, 32, 10, 3, 37, 15, 39, 19, 2, 24, 6, 44, 52, 41, 23, 26, 31, 53, 49, 40, 12, 13, 36, 25]


In [118]:
# DLA
class DLA:
    def __init__(self, x,y):
        self.grid = np.zeros((x,y))
        self.particle_positions = []
        self.history = []
        self.seed_positions = []
        self.x = x
        self.y = y
        
    def initialize_grid(self, num_particles):
        c = ([tuple(x) for x in itertools.combinations_with_replacement(np.arange(10), 2)])
        d = random.sample(range(len(c)),num_particles)
        for i in d:
            self.grid[c[i][0],c[i][1]] = 1 # particles
            self.particle_positions.append((c[i][0],c[i][1]))
        self.grid[self.x//2][self.y//2] = 2 # seed
        self.seed_positions.append((self.x//2, self.y//2))
        
    def grow_particles(self):
        new_positions = []
        for position in self.particle_positions:
            (i,j) = position
            die = random.uniform(0,1)
            if die < 0.25: # go right
                new_position = (i, (j+1)%self.y)
            elif die < 0.5: # go bottom
                new_position = ((i-1)%self.x, j)
            elif die < 0.75: # go left
                new_position = (i, (j-1)%self.y)
            else: # go top
                new_position = ((i+1)%self.x, j)
            self.grid[new_position[0]][new_position[1]] = 1
            new_positions.append(new_position)
        return new_positions
    
    def convert_particles_to_seeds(self, radius):
        for position in self.seed_positions:
            i, j = position
            if self.grid[i][(j+radius)%self.y] == 1:
                self.grid[i][(j+radius)%self.y] = 2
            elif self.grid[i][(j-radius)%self.y] == 1:
                self.grid[i][(j-radius)%self.y] = 2
            elif self.grid[(i-radius)%self.x][j] == 1:
                self.grid[(i-radius)%self.x][j] = 2
            elif self.grid[(i+radius)%self.x][j] == 1:
                self.grid[(i+radius)%self.x][j] = 2
                
    def run_dla(self, steps, radius):
        self.grow_particles()
        self.convert_particles_to_seeds(radius)
        
    def print_grid(self):
            print(self.grid)

In [120]:
dla = DLA(10,10)
dla.initialize_grid(10)
dla.print_grid()
dla.run_dla(10000, 1)
dla.print_grid()

[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0. 1. 0. 1. 1.]
 [0. 0. 0. 0. 0. 2. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 1. 1.]
 [1. 0. 0. 0. 0. 1. 1. 0. 0. 1.]
 [0. 0. 0. 1. 1. 0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 2. 2. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]]
